# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-15 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_level',
        ),
    ]
