# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0003_auto_20181119_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='test', max_length=55),
            preserve_default=False,
        ),
    ]
