# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 22:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg_app', '0003_auto_20181119_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('happiness', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('breed', models.CharField(choices=[('grizzly_bear', 'grizzly_bear'), ('wolves', 'wolves'), ('owls', 'owls'), ('giraffe', 'giraffe'), ('lion', 'lion'), ('rhino', 'rhino'), ('african_elephant', 'african_elephant'), ('polar_bear', 'polar_bear'), ('arctic_fox', 'arctic_fox'), ('penguins', 'penguins'), ('tiger', 'tiger'), ('orangutan', 'orangutan'), ('fruit_bats', 'fruit_bats'), ('asian_elephant', 'asian_elephant')], max_length=55)),
                ('lifespan', models.PositiveSmallIntegerField()),
                ('popularity', models.PositiveSmallIntegerField()),
                ('size', models.PositiveSmallIntegerField()),
                ('location', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('climate', models.CharField(choices=[('arctic', 'arctic'), ('savanna', 'savanna'), ('forest', 'forest'), ('jungle', 'jungle')], max_length=55)),
                ('price', models.PositiveSmallIntegerField()),
                ('popularity', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('location', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('ticket_price', models.PositiveSmallIntegerField(default=5)),
                ('tomorrows_ticket_price', models.PositiveSmallIntegerField(default=5)),
                ('capacity', models.PositiveSmallIntegerField(choices=[(4, 'small'), (6, 'medium'), (8, 'large')])),
                ('current_weather', models.PositiveSmallIntegerField(choices=[(1, 'overcast'), (2, 'sunny'), (3, 'rainy'), (4, 'stormy')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoos', to='logreg_app.Users')),
            ],
        ),
        migrations.AddField(
            model_name='habitat',
            name='zoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='zoo_app.Zoo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhabitants', to='zoo_app.Habitat'),
        ),
    ]
