# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='zoo',
            name='price',
        ),
    ]
