# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0003_auto_20181119_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(choices=[('grizzly_bear', 'Grizzly Bear'), ('wolf', 'Wolf'), ('owl', 'Owl'), ('giraffe', 'Giraffe'), ('lion', 'Lion'), ('rhino', 'Rhino'), ('african_elephant', 'African Elephant'), ('polar_bear', 'Polar Bear'), ('arctic_fox', 'Arctic Fox'), ('penguin', 'Penguin'), ('tiger', 'Tiger'), ('orangutan', 'Orangutan'), ('fruit_bat', 'Fruit Bat'), ('asian_elephant', 'Asian Elephant')], max_length=55),
        ),
    ]
