# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0004_auto_20181120_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day', models.PositiveSmallIntegerField(null=True)),
                ('resolution_day', models.PositiveSmallIntegerField(null=True)),
                ('event_data1', models.PositiveSmallIntegerField(null=True)),
                ('event_data2', models.PositiveSmallIntegerField(null=True)),
                ('event_data3', models.PositiveSmallIntegerField(null=True)),
                ('event_message', models.TextField()),
                ('resolution_message', models.TextField()),
                ('affected_animals', models.ManyToManyField(related_name='events', to='zoo_app.Animal')),
                ('exhibits', models.ManyToManyField(related_name='events', to='zoo_app.Habitat')),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='zoo_app.Zoo')),
            ],
        ),
    ]
